---
author: 'Aydın Doyak'
description: 'Folyolar'
email: 'aydintd@bil.omu.edu.tr'
url: 'fo.aydintd.me'
domain: 'aydintd.me'
intro: ''
googleanalytics: ''
googleplus: ''
brand: default
landslide: /usr/bin/landslide
css: _/default.css
js: _/default.js
theme: light
indextemplate: _/index.erb
foliotemplate: _/default.erb
